[package]
name = "todomvc"
version = "0.1.0"
authors = ["Pauan <pcxunlimited@gmail.com>"]

[dependencies]
dominator = { path = "../.." }
signals = { path = "../../signals" }

[dependencies.stdweb]
path = "../../../stdweb"
features = ["experimental_features_which_may_break_on_minor_version_bumps"]
