[package]
name = "todomvc"
version = "0.1.0"
authors = ["Pauan <pcxunlimited@gmail.com>"]

[dependencies]
dominator = { path = "../.." }
signals = "0.1.0"
serde = "1.0.27"
serde_json = "1.0.10"
serde_derive = "1.0.27"

[dependencies.stdweb]
version = "0.4.0"
features = ["experimental_features_which_may_break_on_minor_version_bumps"]
