[package]
name = "dominator"
version = "0.1.0"
authors = ["Pauan <pcxunlimited@gmail.com>"]

[dependencies]
stdweb-derive = "0.4.0"
lazy_static = "1.0.0"
discard = "1.0.3"
signals = { path = "./signals" }

[dependencies.stdweb]
version = "0.4.0"
features = ["experimental_features_which_may_break_on_minor_version_bumps"]
