[package]
name = "dominator"
version = "0.1.1"
authors = ["Pauan <pcxunlimited@gmail.com>"]
description = "Zero cost virtual DOM library using FRP signals"
repository = "https://github.com/Pauan/rust-dominator"
homepage = "https://github.com/Pauan/rust-dominator"
readme = "README.md"
license = "MIT"
keywords = ["javascript", "dom", "reactive", "signal", "frp"]
categories = ["web-programming", "template-engine", "wasm"]

[dependencies]
stdweb-derive = "0.4.0"
lazy_static = "1.0.0"
discard = "1.0.3"
futures-core = "0.2.0"
#futures-signals = { path = "../rust-signals" }
futures-signals = { git = "https://github.com/Pauan/rust-signals" }

[dependencies.stdweb]
version = "0.4.6"
#git = "https://github.com/koute/stdweb"
#path = "../stdweb"
features = ["experimental_features_which_may_break_on_minor_version_bumps"]

[profile.release]
debug-assertions = true

[profile.bench]
debug-assertions = true
