[package]
name = "animation"
version = "0.1.0"
authors = ["Pauan <pcxunlimited@gmail.com>"]

[dependencies]
dominator = { path = "../.." }
signals = { git = "https://github.com/Pauan/rust-signals" }

[dependencies.stdweb]
version = "0.4.0"
features = ["experimental_features_which_may_break_on_minor_version_bumps"]
